### ISSUE TITLE
builds failing due to missing upstream code

### ISSUE THREAD

**Issue by realchrisolin** [ResurrectionRemix/cm_platform_sdk#8]
`ERROR: /home/colin/android/rr/mm/frameworks/opt/hardware/src/org/cyanogenmod/hardware/PictureAdjustment.java:22: The import cyanogenmod.hardware.HSIC cannot be resolved ERROR: /home/colin/android/rr/mm/frameworks/opt/hardware/src/org/cyanogenmod/hardware/PictureAdjustment.java:47: HSIC cannot be resolved to a type ERROR: /home/colin/android/rr/mm/frameworks/opt/hardware/src/org/cyanogenmod/hardware/PictureAdjustment.java:59: HSIC cannot be resolved to a type ERROR: /home/colin/android/rr/mm/frameworks/opt/hardware/src/org/cyanogenmod/hardware/PictureAdjustment.java:71: HSIC cannot be resolved to a type make: *** [/home/colin/android/rr/mm/out/target/common/obj/JAVA_LIBRARIES/org.cyanogenmod.hardware_intermediates/with-local/classes.dex] Error 41`

cyanogenmod.hardware.HISC was added in http://review.cyanogenmod.org/#/c/153538 -- please cherry pick

**Comment by ashishkotnala29** [comment]
I confirm the above

**Comment by realchrisolin** [comment]
fixed with https://github.com/ResurrectionRemix/cm_platform_sdk/commit/1d1a6e5719833b8b2f2b9eb9dd7c864b3639206a
